//! Minimum viable demo of the atsamd-hal RTC monotonic unbounded-spin bug.
//!
//! # Bug Summary
//!
//! The RTC monotonic interrupt handler generated by `__internal_backend_methods!`
//! (`hal/src/rtc/rtic/backends.rs`) contains a "catch-up" spin meant to absorb
//! the RTC `COUNT` read-synchronization delay (a few ticks):
//!
//! ```ignore
//! if <$mode>::check_interrupt_flag::<$rtic_int>(&rtc) {
//!     let compare = <$mode>::get_compare(&rtc, 0);
//!     while less_than_with_wrap(<$mode>::count(&rtc), compare) {}
//! }
//! ```
//!
//! It reads **CC0 live** instead of the compare value that actually raised the
//! flag. CC0 is not stable across handler entry:
//!
//! * `rtic-time`'s timer queue re-arms CC0 whenever a newly inserted deadline
//!   becomes the queue head.
//! * The handler is also entered by software: `Delay::poll` calls
//!   `Backend::pend_interrupt()` (`NVIC::pend(RTC)`) on that same head update,
//!   and dropping a `Delay` removes its deadline without touching CC0.
//!
//! So the handler can be entered with `INTFLAG.CMP0` still set from a compare
//! that already fired while CC0 has been re-armed to a *later* deadline — and
//! the spin then runs all the way to that later deadline.
//!
//! # Why it is severe
//!
//! RTIC pins the monotonic IRQ at `min(hardware task priority) - 1`, i.e.
//! **equal to the highest-priority async software task in the application**.
//! On Cortex-M, equal priority means no preemption: while the spin runs, the
//! application's most timing-critical async tasks are frozen — no lock taken,
//! no shared resource involved. The freeze length is bounded only by the
//! application's own longest queued deadline.
//!
//! # Demo structure
//!
//! | Task          | Prio | Role                                                |
//! |---------------|------|-----------------------------------------------------|
//! | `message_isr` | 3 hw | "byte arrived" ISR; forces RTC vector to prio 2     |
//! | `responder`   | 2    | re-arms a 2 s timeout per message (`select_biased!`)|
//! | `control_loop`| 1    | `delay_until` loop; its deadline sits in CC0        |
//!
//! SysTick (above priority 3) stands in for the wire, pending TC2 at `MSG_HZ`.
//!
//! Each timeout re-arm inserts a timer-queue deadline; when the insert pends
//! the RTC vector inside the window where `INTFLAG.CMP0` is still set from the
//! control loop's compare and CC0 has been re-armed, the spin runs to the
//! deadline in CC0 and everything at priority <= 2 freezes — for up to one
//! control-loop period. The cadences are compressed relative to the field
//! case that surfaced the bug (500 ms loop, ~1 kHz messages -> ~500 ms stalls)
//! to raise incidence; the mechanism is cadence-independent. The responder
//! measures its own iteration time in SysTick-driven wire ticks
//! (RTC-independent, and the tick ISRs outprioritize the RTC vector so they
//! keep counting through a stall — proving priority 3 stayed alive) and
//! reports stalls.
//!
//! # Running
//!
//! ```sh
//! # Show the bug: intermittent [STALL] reports, incidence scales with
//! # message rate. Leave it running for a few minutes.
//! cargo embed
//!
//! # Show the fix: uncomment the [patch.crates-io] section in Cargo.toml to
//! # build against the fork with the bounded catch-up spin, then:
//! cargo embed
//! ```
//!
//! # Expected Output
//!
//! With the crates.io HAL, `[STALL] responder frozen for X ms` lines (X up to
//! one `CTRL_PERIOD`) appear intermittently between `[status]` summaries; the
//! message ISR count keeps advancing during each stall. With the patched HAL,
//! no stalls are reported.
//!
//! # Target
//!
//! ATSAMD51J20A (Cortex-M4F), XOSC32K crystal on PA00/PA01, plain-text RTT.

#![no_std]
#![no_main]

use core::sync::atomic::{AtomicU32, Ordering};
use panic_halt as _;

/// CPU frequency in Hz. Default DFLL at reset, no DPLL configured.
const CPU_HZ: u32 = 48_000_000;

/// "Message" rate on the simulated wire, Hz. Each message makes the responder
/// drop and re-arm its timeout; stall incidence scales with this, but so does
/// priority-2 load. The budget that matters is the DEGENERATE state entered
/// after every control-loop fire (timeout at the queue head), where each
/// message costs PROC_CYCLES plus a full head-update set_compare — measured
/// at ~300-500 µs on hardware. That must stay well under the message period
/// or priority 1 starves and the control loop never re-inserts (matches the
/// field cadence, too).
const MSG_HZ: u32 = 1_000;

/// Message-phase dither, in CPU cycles (±100 µs). The field wire was jittery;
/// a rigidly periodic message stream steps through the control loop's fire
/// window in fixed beat increments and can permanently miss a sub-µs
/// alignment window. The SysTick handler re-writes its reload each tick with
/// this much pseudo-random offset so the probe phase random-walks instead.
const MSG_JITTER_CYCLES: u32 = 4_800;

/// Milliseconds since boot, kept by SysTick. Independent of the RTC.
static SYSTICK_MS: AtomicU32 = AtomicU32::new(0);
/// Times the priority-3 message ISR has fired.
static ISR_FIRED: AtomicU32 = AtomicU32::new(0);
/// Messages dropped because the responder's channel was full (responder frozen).
static MSG_DROPPED: AtomicU32 = AtomicU32::new(0);
/// Messages the responder handled.
static MSG_HANDLED: AtomicU32 = AtomicU32::new(0);
/// Control loop iterations — heartbeat visibility for priority-1 starvation.
static CTRL_ITERS: AtomicU32 = AtomicU32::new(0);
/// Pacer iterations — if this stops advancing, near-coincident arms stop and
/// the repro silently loses its trigger, so the heartbeat reports it.
static PACER_ITERS: AtomicU32 = AtomicU32::new(0);
/// Consecutive heartbeats in the lost-wake condition (COUNT past CC0, flag
/// clear). See the detector in `message_isr`.
static LOST_WAKE_BEATS: AtomicU32 = AtomicU32::new(0);
/// Stall events observed by the responder.
static STALLS: AtomicU32 = AtomicU32::new(0);
/// Worst observed stall, microseconds.
static WORST_STALL_US: AtomicU32 = AtomicU32::new(0);
/// Longest responder iteration in the current status window, microseconds.
/// Makes sub-threshold anomalies visible; reset at each status print.
static PEAK_ITER_US: AtomicU32 = AtomicU32::new(0);

/// Stands in for the RS485 wire: pends the priority-3 "message received"
/// interrupt at `MSG_HZ`. Runs above priority 3 so it keeps firing while the
/// buggy spin blocks priority <= 2.
#[cortex_m_rt::exception]
fn SysTick() {
    static mut DIV: u32 = 0;
    static mut RNG: u32 = 0x1234_5678;

    *DIV += 1;
    if *DIV >= MSG_HZ / 1_000 {
        *DIV = 0;
        SYSTICK_MS.fetch_add(1, Ordering::Relaxed);
    }

    // xorshift32 -> dither the next tick's period by ±MSG_JITTER_CYCLES.
    let mut x = *RNG;
    x ^= x << 13;
    x ^= x >> 17;
    x ^= x << 5;
    *RNG = x;
    let base = CPU_HZ / MSG_HZ - 1;
    let offset = x % (2 * MSG_JITTER_CYCLES);
    unsafe {
        (*cortex_m::peripheral::SYST::PTR)
            .rvr
            .write(base - MSG_JITTER_CYCLES + offset);
    }

    cortex_m::peripheral::NVIC::pend(atsamd_hal::pac::Interrupt::TC2);
}

#[rtic::app(device = atsamd_hal::pac, dispatchers = [TC0, TC1])]
mod app {
    use super::*;
    use atsamd_hal::{
        clock::v2::{
            clock_system_at_reset,
            rtcosc::RtcOsc,
            xosc32k::{ControlGainMode, StartUpDelay, Xosc32k, Xosc32kBase},
        },
        gpio,
        rtc::rtic::rtc_clock,
        rtc_monotonic,
        rtic_time::Monotonic,
    };
    use core::{
        future::{Future, poll_fn},
        pin::pin,
        task::Poll,
    };
    use cortex_m::peripheral::{DWT, scb::SystemHandler, syst::SystClkSource};
    use rtic_sync::{
        channel::{Receiver, Sender},
        make_channel,
    };
    use rtt_target::{rprintln, rtt_init_print};

    rtc_monotonic!(RtcMono, rtc_clock::Clock32k);

    type RtcDuration = <RtcMono as Monotonic>::Duration;

    /// Control loop period. Its `delay_until` deadline is what sits in CC0
    /// most of the time — the value the buggy catch-up spin runs to. Every
    /// compare fire opens one race window, so incidence scales inversely with
    /// this; the field case was 500 ms, compressed here for repro speed.
    /// Stalls last up to one period.
    const CTRL_PERIOD: RtcDuration = RtcDuration::millis(50);
    /// Responder timeout, dropped and re-armed on every message.
    const RESP_TIMEOUT: RtcDuration = RtcDuration::secs(2);
    /// Pacer period, modeling the field firmware's other short-delay
    /// monotonic users (ADC pacing, thermal loop, ...). 7 ms = 229 ticks;
    /// 1638 mod 229 = 35, so pacer deadlines sweep phase against the control
    /// loop in ~35-tick steps and land within the ~6-tick sync horizon of a
    /// control deadline every few fires. Those near-coincident pairs are what
    /// drive the timer queue through set_compare's near-now bump path and the
    /// guard-continue re-arm — the documented-physics route to entering the
    /// handler with CMP0 stale-set while CC0 holds a far deadline.
    const PACER_PERIOD: RtcDuration = RtcDuration::millis(7);
    /// Depth of the message ISR -> responder channel.
    const MSG_CAP: usize = 8;
    /// Priority-2 busy time per message, modeling the field responder's
    /// parse/respond work. This is a key repro ingredient: it delays the
    /// priority-1 control loop's deadline re-insert after a compare fire,
    /// holding a far deadline in CC0 across message arrivals — the window
    /// the race needs.
    const PROC_CYCLES: u32 = (CPU_HZ / 1_000_000) * 100; // 100 µs
    /// Priority-1 busy time per control iteration, modeling the field control
    /// task's per-period work. Equally load-bearing: it holds the control
    /// loop's re-insert open after each compare fire, so the
    /// far-deadline-in-CC0 window is wider than the message/loop beat's phase
    /// step (~36 µs/fire) and gets probed on every sweep pass instead of
    /// being jumped over.
    const CTRL_WORK_CYCLES: u32 = (CPU_HZ / 1_000_000) * 200; // 200 µs
    /// Responder iterations longer than this many wire ticks (1/MSG_HZ s
    /// each) are reported as stalls. Normal iterations are ~1-2 ticks.
    const STALL_THRESHOLD_TICKS: u32 = MSG_HZ * 5 / 1_000; // 5 ms
    /// Microseconds per wire tick.
    const TICK_US: u32 = 1_000_000 / MSG_HZ;

    #[shared]
    struct Shared {}

    #[local]
    struct Local {
        tx: Sender<'static, (), MSG_CAP>,
    }

    #[init]
    fn init(ctx: init::Context) -> (Shared, Local) {
        rtt_init_print!();

        let mut core = ctx.core;
        let mut device = ctx.device;

        // Cycle counter, used only for the boot-time self-check: some
        // Cortex-M4 implementations gate DWT behind the lock register, so
        // unlock before enabling. Stall timing runs on SysTick wire ticks
        // and does not depend on this.
        core.DCB.enable_trace();
        cortex_m::peripheral::DWT::unlock();
        core.DWT.enable_cycle_counter();

        // Minimum clock setup: XOSC32K crystal -> RTC monotonic
        let (_bus, _clocks, tokens) = clock_system_at_reset(
            device.oscctrl,
            device.osc32kctrl,
            device.gclk,
            device.mclk,
            &mut device.nvmctrl,
        );

        let pins = gpio::Pins::new(device.port);
        let xosc32k_base = Xosc32kBase::from_crystal(tokens.xosc32k.base, pins.pa00, pins.pa01)
            .start_up_delay(StartUpDelay::Delay1s)
            .control_gain_mode(ControlGainMode::HighSpeed)
            .on_demand(false)
            .run_standby(true)
            .enable();
        while !xosc32k_base.is_ready() {
            cortex_m::asm::nop();
        }
        let (xosc32k, xosc32k_base) = Xosc32k::enable(tokens.xosc32k.xosc32k, xosc32k_base);
        xosc32k_base.write_lock();

        let (_rtc_osc, _xosc32k) = RtcOsc::enable(tokens.rtcosc, xosc32k);
        RtcMono::start(device.rtc);

        // Measure the COUNT read-sync granularity: the synced copy advances
        // in steps (upstream docs: "typically increments by four"); the max
        // observed step bounds the refresh quantum that SYNC_SLACK_TICKS must
        // comfortably exceed. The CYCCNT delta across the same loop is a
        // self-check that the cycle counter actually runs on this silicon.
        let cyc0 = DWT::cycle_count();
        let mut prev = RtcMono::now().ticks();
        let end = prev + 8192; // ~250 ms at 32.768 kHz
        let (mut max_step, mut updates) = (0u64, 0u32);
        loop {
            let c = RtcMono::now().ticks();
            if c != prev {
                max_step = max_step.max(c - prev);
                updates += 1;
                prev = c;
            }
            if c >= end {
                break;
            }
        }

        // SysTick as the simulated wire, above the priority-3 message ISR
        // (logical 4 -> hw 0x80) so it preempts the spin like the field's EIC.
        unsafe { core.SCB.set_priority(SystemHandler::SysTick, 0x80) };
        let mut syst = core.SYST;
        syst.set_clock_source(SystClkSource::Core);
        syst.set_reload(CPU_HZ / MSG_HZ - 1);
        syst.clear_current();
        syst.enable_counter();
        syst.enable_interrupt();

        let (tx, rx) = make_channel!((), MSG_CAP);

        let rtc_prio =
            cortex_m::peripheral::NVIC::get_priority(atsamd_hal::pac::Interrupt::RTC);

        rprintln!("=== atsamd-hal RTC monotonic unbounded-spin demo ===");
        rprintln!("RTC monotonic: 32768 Hz (XOSC32K)");
        rprintln!(
            "RTC vector NVIC priority: {:#04x} (logical {})",
            rtc_prio,
            8 - (rtc_prio >> 5)
        );
        rprintln!(
            "COUNT sync granularity: max step {} ticks over {} updates in ~250ms",
            max_step,
            updates
        );
        rprintln!(
            "CYCCNT over the same window: {} (expect ~12M; 0 = DWT dead)",
            DWT::cycle_count().wrapping_sub(cyc0)
        );
        rprintln!();
        rprintln!(
            "control_loop (prio 1): {}ms delay_until loop",
            CTRL_PERIOD.to_millis()
        );
        rprintln!(
            "responder    (prio 2): re-arms a {}s timeout per message, {}Hz",
            RESP_TIMEOUT.to_secs(),
            MSG_HZ
        );
        rprintln!("message_isr  (prio 3): keeps firing during any stall");
        rprintln!();
        rprintln!(
            "Watch for [STALL] lines: responder frozen ~{}ms while the RTC",
            CTRL_PERIOD.to_millis()
        );
        rprintln!("handler spins to a re-armed CC0. May take minutes to hit.");
        rprintln!();

        control_loop::spawn().ok();
        pacer::spawn().ok();
        responder::spawn(rx).ok();

        (Shared {}, Local { tx })
    }

    /// "Message received" ISR — stands in for the field's RS485 SERCOM/EIC
    /// interrupts. Its existence at priority 3 also forces RTIC to place the
    /// RTC monotonic vector at logical priority 2 (`min(hw prio) - 1`), level
    /// with the responder's dispatcher.
    #[task(binds = TC2, priority = 3, local = [tx])]
    fn message_isr(ctx: message_isr::Context) {
        let fired = ISR_FIRED.fetch_add(1, Ordering::Relaxed).wrapping_add(1);
        if ctx.local.tx.try_send(()).is_err() {
            MSG_DROPPED.fetch_add(1, Ordering::Relaxed);
        }

        // 1 Hz heartbeat from priority 3: immune to any freeze at <= 2, and
        // reads the RTC registers directly so a handler stuck in the catch-up
        // spin is visible from outside (CMP0 set, COUNT well below CC0,
        // handled frozen).
        if fired % MSG_HZ == 0 {
            let rtc = unsafe { atsamd_hal::pac::Rtc::steal() };
            let m0 = rtc.mode0();
            let count = m0.count().read().bits();
            let cc0 = m0.comp(0).read().bits();
            let cmp0 = m0.intflag().read().cmp0().bit();
            rprintln!(
                "[hb] fired={} handled={} ctrl={} pacer={} dropped={} COUNT={} CC0={} CMP0={}",
                fired,
                MSG_HANDLED.load(Ordering::Relaxed),
                CTRL_ITERS.load(Ordering::Relaxed),
                PACER_ITERS.load(Ordering::Relaxed),
                MSG_DROPPED.load(Ordering::Relaxed),
                count,
                cc0,
                cmp0 as u8,
            );

            // Lost-wake detector: the compare matches on equality only, so an
            // armed CC0 that COUNT has passed with the flag clear can never
            // fire — the timer queue is dead. Requiring two consecutive beats
            // filters the benign µs window between flag-clear and re-arm
            // inside the handler; cc0 != 0 filters the COMP0 mid-write-sync
            // readback artifact.
            let past = count.wrapping_sub(cc0);
            if !cmp0 && cc0 != 0 && past > 64 && past < 0x8000_0000 {
                let n = LOST_WAKE_BEATS.fetch_add(1, Ordering::Relaxed) + 1;
                if n >= 2 {
                    rprintln!(
                        "[LOST-WAKE] CC0={} passed by COUNT={} with CMP0 clear ({}s) — compare can never fire",
                        cc0,
                        count,
                        n,
                    );
                }
            } else {
                LOST_WAKE_BEATS.store(0, Ordering::Relaxed);
            }
        }
    }

    /// Control loop at priority 1. Runs `delay_until` on a fixed 500 ms
    /// cadence; between handler runs its next deadline is the timer-queue head
    /// and therefore the live contents of CC0.
    #[task(priority = 1)]
    async fn control_loop(_ctx: control_loop::Context) {
        let mut iters = 0u32;
        let mut next = RtcMono::now();
        loop {
            next += CTRL_PERIOD;
            RtcMono::delay_until(next).await;
            iters += 1;
            CTRL_ITERS.store(iters, Ordering::Relaxed);

            // Priority-1 "control task" work for this period (see
            // CTRL_WORK_CYCLES — this is what holds the race window open).
            cortex_m::asm::delay(CTRL_WORK_CYCLES);

            let late = RtcMono::now() - next;
            if late.to_millis() > 5 {
                rprintln!("[ctrl] iteration {} late by {}ms", iters, late.to_millis());
            }

            if iters % 200 == 0 {
                rprintln!(
                    "[status] t={}s handled={} stalls={} worst={}us peak={}us dropped={}",
                    SYSTICK_MS.load(Ordering::Relaxed) / 1_000,
                    MSG_HANDLED.load(Ordering::Relaxed),
                    STALLS.load(Ordering::Relaxed),
                    WORST_STALL_US.load(Ordering::Relaxed),
                    PEAK_ITER_US.swap(0, Ordering::Relaxed),
                    MSG_DROPPED.load(Ordering::Relaxed),
                );
            }
        }
    }

    /// Short-delay pacer at priority 1 (see [`PACER_PERIOD`]): supplies the
    /// near-coincident deadline pairs that push the timer queue through the
    /// near-now arming path.
    #[task(priority = 1)]
    async fn pacer(_ctx: pacer::Context) {
        loop {
            RtcMono::delay(PACER_PERIOD).await;
            PACER_ITERS.fetch_add(1, Ordering::Relaxed);
        }
    }

    /// RS485-responder stand-in at priority 2 — the same priority the RTC
    /// vector lands on, so the buggy spin blocks it with no preemption.
    ///
    /// Every message races a fresh 2 s timeout against the channel, exactly
    /// like `select_biased!` in a request/timeout loop: the timeout `Delay` is
    /// polled once (inserting its deadline into the timer queue, pending the
    /// RTC vector if it became the head) and dropped when the message wins
    /// (removing the deadline; CC0 is left as-is). When one of those inserts
    /// pends the RTC vector inside the race window, the responder freezes for
    /// however far away the deadline sitting in CC0 is.
    #[task(priority = 2)]
    async fn responder(_ctx: responder::Context, mut rx: Receiver<'static, (), MSG_CAP>) {
        // Bootstrap: yield once before entering the message loop so the
        // priority-1 control loop gets its first `delay_until` deadline into
        // the timer queue. Without this the queue holds only our 2 s timeout,
        // every re-insert is a head update, and the resulting per-message
        // set_compare (two SYNCBUSY waits at priority 2) can saturate
        // priority 2 before priority 1 ever runs.
        RtcMono::delay(RtcDuration::millis(10)).await;

        loop {
            // Iteration time in wire ticks: SysTick-driven, independent of
            // both the RTC and DWT, and keeps counting through any stall
            // (SysTick and the message ISR outprioritize the RTC vector).
            let t0_tick = ISR_FIRED.load(Ordering::Relaxed);

            // select_biased! { _ = rx.recv() => false, _ = delay(2s) => true }
            let timed_out = {
                let mut msg = pin!(rx.recv());
                let mut timeout = pin!(RtcMono::delay(RESP_TIMEOUT));
                poll_fn(|cx| {
                    if msg.as_mut().poll(cx).is_ready() {
                        return Poll::Ready(false);
                    }
                    if timeout.as_mut().poll(cx).is_ready() {
                        return Poll::Ready(true);
                    }
                    Poll::Pending
                })
                .await
                // `timeout` drops here: its deadline leaves the timer queue
            };

            let dt_ticks = ISR_FIRED.load(Ordering::Relaxed).wrapping_sub(t0_tick);
            let dt_us = dt_ticks * TICK_US;

            if timed_out {
                rprintln!("[timeout] no message for 2s (wire runs at {}Hz!)", MSG_HZ);
                continue;
            }
            MSG_HANDLED.fetch_add(1, Ordering::Relaxed);

            PEAK_ITER_US.fetch_max(dt_us, Ordering::Relaxed);

            if dt_ticks > STALL_THRESHOLD_TICKS {
                STALLS.fetch_add(1, Ordering::Relaxed);
                WORST_STALL_US.fetch_max(dt_us, Ordering::Relaxed);
                rprintln!(
                    "[STALL] responder frozen for {}.{:03}ms ({} wire ticks; prio-3 ISR kept firing)",
                    dt_us / 1_000,
                    dt_us % 1_000,
                    dt_ticks,
                );
            }

            // Priority-2 "parse/respond" work for this message. asm::delay
            // is instruction-counted — no DWT dependence, always terminates.
            cortex_m::asm::delay(PROC_CYCLES);
        }
    }
}
